# Generated by Django 2.2.4 on 2019-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companeros_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apellido materno')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('domicilio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Domicilio')),
                ('empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Empresa')),
                ('area', models.CharField(blank=True, choices=[('areaA', 'Área A'), ('areaB', 'Área B')], max_length=10, null=True, verbose_name='Área')),
                ('rubro_empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rubro empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apellido materno')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('domicilio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Domicilio')),
                ('status', models.CharField(blank=True, choices=[('familiar', 'familiar'), ('amigo', 'amigo')], max_length=10, null=True, verbose_name='Amigo/Familiar')),
            ],
        ),
    ]
